import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbarr from "@/components/ui/Navbarr";
import Footer from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        <div className="">
          <Navbarr/>
          {children}
          <Footer />
        </div>
      </Provider>
      </body>
    </html>
  );
}
